sudo: required
language:  python
dist: trusty

matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
    - os: linux
      dist: trusty
      python: 3.5
    - os: linux
      dist: trusty
      python: 3.6
      #    - os: linux
      #dist: xenial
      #python: 3.7
    - os: linux
      dist: trusty
      python: pypy-5.4.1


install:
  - pip install zc.buildout
  - pip install setuptools==36.8.0
  - buildout bootstrap
  - buildout

script:
  - bin/test

