sudo: false
language:  python

matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
    - os: linux
      dist: trusty
      python: 3.5
    - os: linux
      dist: trusty
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7
    - os: linux
      dist: trusty
      python: pypy-5.4.1


https://travis-ci.org/PyFilesystem/webdavfs/builds/408064519

install:
  - pip install zc.buildout
  - pip install setuptools==36.8.0
  - buildout bootstrap
  - buildout

script:
  - bin/test


notifications:
  irc:
    channels:
      - "irc.freenode.org#sprint"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
