language:  python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy-5.4.1

install:
  - pip install zc.buildout
  - pip install setuptools==36.8.0
  - buildout bootstrap
  - buildout

script:
  - bin/test


notifications:
  irc:
    channels:
      - "irc.freenode.org#sprint"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
